name: DGC-AutoBuild

on:
  release:
    types: [published, prereleased]
  workflow_dispatch:

jobs:
  build-executable-v1:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller pylo.py --onefile --console

      - name: Rename and zip binary
        shell: bash
        run: |
          mkdir upload
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv dist/pylo.exe upload/pylo-windows.exe
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mv dist/pylo upload/pylo-macos
            cd upload && zip pylo-macos.zip pylo-macos
          else
            mv dist/pylo upload/pylo-linux
            cd upload && zip pylo-linux.zip pylo-linux
          fi
      
      - name: Zip on Windows (Compress-Archive)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Compress-Archive -Path upload/pylo-windows.exe -DestinationPath upload/pylo-windows.zip

      - name: Get latest release tag
        id: get_release
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          latest_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*.zip
          tag_name: ${{ github.event_name == 'workflow_dispatch' && env.LATEST_TAG || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  build-executable-v2:
    needs: build-executable-v1
    strategy:
      matrix:
        os: [macos-latest, macos-13, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka ordered-set zstandard pefile

      - name: Build with Nuitka
        shell: bash
        run: |
          python -m nuitka \
            --standalone \
            --onefile \
            --output-dir=dist \
            --remove-output \
            --enable-plugin=pylint-warnings \
            --assume-yes-for-downloads \
            pylo.py

      - name: Rename and zip binary
        shell: bash
        run: |
          mkdir upload
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv dist/pylo.exe upload/pylo-windows-amd64.exe
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mv dist/pylo.bin upload/pylo-macos-arm64
            cd upload && zip pylo-macos-arm64.zip pylo-macos-arm64
          elif [[ "${{ matrix.os }}" == "macos-13" ]]; then
            mv dist/pylo.bin upload/pylo-macos-amd64
            cd upload && zip pylo-macos-amd64.zip pylo-macos-amd64
          else
            mv dist/pylo.bin upload/pylo-linux-amd64
            cd upload && zip pylo-linux-amd64.zip pylo-linux-amd64
          fi
      
      - name: Zip on Windows (Compress-Archive)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Compress-Archive -Path upload/pylo-windows-amd64.exe -DestinationPath upload/pylo-windows-amd64.zip

      - name: Get latest release tag
        id: get_release
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: |
          latest_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*.zip
          tag_name: ${{ github.event_name == 'workflow_dispatch' && env.LATEST_TAG || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  update-version-txt:
    needs: build-executable-v2
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git
        run: |
          git config user.name "DGC-BuildBot"
          git config user.email "bot@diamondgotcat.net"

      - name: Determine release tag
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          else
            tag="${{ github.ref_name }}"
          fi
          echo "TAG_NAME=$tag" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Update version.txt with release tag
        if: (github.event_name == 'release' && !github.event.release.prerelease) || github.event_name == 'workflow_dispatch'
        run: |
          echo "$TAG_NAME" > version.txt
          git add version.txt
          git commit -m "Update version.txt to $TAG_NAME" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:main
