name: Build Executable

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller pylo.py --onefile --noconsole

      - name: Rename and zip binary
        shell: bash
        run: |
          mkdir upload
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv dist/pylo.exe upload/pylo-windows.exe
            cd upload && zip pylo-windows.zip pylo-windows.exe
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mv dist/pylo upload/pylo-macos
            cd upload && zip pylo-macos.zip pylo-macos
          else
            mv dist/pylo upload/pylo-linux
            cd upload && zip pylo-linux.zip pylo-linux
          fi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
